import ts from 'typescript';
import fs from 'node:fs';
import assert from 'node:assert/strict';
fs.mkdirSync('work',{recursive:true});
for(const name of ['physics','simulator']){let src=fs.readFileSync(`app/${name}.ts`,'utf8').replace("'./physics'","'./physics.mjs'");fs.writeFileSync(`work/${name}.mjs`,ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText)}
const {Simulator}=await import('../work/simulator.mjs');
const THREE=await import('three');const {default:RAPIER}=await import('@dimforge/rapier3d-compat');const P=await import('../work/physics.mjs');await RAPIER.init();
const s=Object.create(Simulator.prototype);Object.assign(s,{world:new RAPIER.World({x:0,y:-9.81,z:0}),scene:new THREE.Scene(),robotMesh:new THREE.Group(),turret:new THREE.Group(),wheels:[],balls:[],gates:[],inventory:[],ramp:[],keys:new Set(),s:{},options:{assist:true,power:6.3,view:'Field',sound:false,timed:false},padButtons:[],yaw:0,shotClock:0,cb:()=>{},label:()=>{}});s.world.timestep=1/120;s.buildField();s.buildRobot();s.reset();
assert.equal(s.balls.length,36);assert.equal(s.balls.filter(b=>b.color==='G').length,12);assert.equal(s.inventory.length,3);
s.s.running=true;for(let i=0;i<120;i++)s.step();s.shoot();for(let i=0;i<240;i++)s.step();console.log('Shot result',s.s.score,s.s.message,s.balls.filter(b=>b.state==='flight').map(b=>b.body.translation()));assert.equal(s.s.classified,1,'assisted shot should enter the goal and classify');assert.equal(s.ramp.length,1);
// Gate release: physically place robot at the accessible gate actuation area.
s.robot.setTranslation({x:1.26,y:.14,z:.39},true);s.robot.setLinvel({x:0,y:0,z:0},true);s.keys.add('KeyF');for(let i=0;i<720;i++)s.step();assert(s.s.gate>.8,'gate opens only when nearby and held');assert.equal(s.ramp.length,0,'classified artifact rolls out of the open gate');s.keys.clear();for(let i=0;i<240;i++)s.step();assert(s.s.gate<.1,'released gate closes under gravity');
s.reset();s.s.running=true;s.keys.add('KeyD');for(let i=0;i<1000;i++)s.step();assert(s.robot.translation().x<1.7,'wall stops robot');s.keys.clear();s.reset();s.s.running=true;s.robot.setTranslation({x:0,y:.14,z:.5},true);s.shoot();assert.equal(s.s.shots,0,'shots outside launch zones are blocked');
assert.equal(P.patternPoints(['G','P','P','P','G','P']),8);assert.equal(P.deadzone(.1),0);let impulse=P.driveImpulse({x:0,z:0},{x:5,z:5},14,1/120);assert(Math.hypot(impulse.x,impulse.z)<=14*4.7/120+1e-10);s.reset();s.options.timed=true;s.s.running=true;s.s.time=.02;for(let i=0;i<5;i++)s.step();assert(s.s.ended);assert(!s.s.running);s.reset();s.s.running=true;const pad={connected:true,mapping:'standard',axes:[1,0,0,0],buttons:Array.from({length:16},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{value:()=>[pad],configurable:true});for(let i=0;i<60;i++)s.step();assert(s.robot.translation().x>.2,'left stick drives the robot');pad.axes=[0,0,0,0];pad.buttons[9].pressed=true;s.step();assert(!s.s.running,'Options pauses');pad.buttons[9].pressed=false;s.step();pad.buttons[9].pressed=true;s.step();assert(s.s.running,'Options resumes');s.world.free();console.log('PASS: ball count, assisted scoring, physical gate release, gravity closure, wall collision, launch restriction, pattern scoring, traction cap, and timer.');
