'use client';
import { useEffect, useRef, useState } from 'react';
import { Gamepad2, RotateCcw, Pause, Play, Crosshair, Maximize, Keyboard, ChevronRight, Volume2, VolumeX, ArrowUpRight } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import type { Simulator, Snapshot } from './simulator';
const initial: Snapshot = { ready:false, score:0, classified:0, overflow:0, pattern:0, magazine:['P','G','P'], ramp:[], speed:0, time:120, running:false, gate:0, nearGate:false, controller:'', message:'Preparing field…', shots:0, hits:0, ended:false, inZone:true };
export default function Home(){
 const mount=useRef<HTMLDivElement>(null), sim=useRef<Simulator|null>(null);
 const [s,setS]=useState(initial), [assist,setAssist]=useState(true), [power,setPower]=useState(6.3), [view,setView]=useState('Field'), [sound,setSound]=useState(true), [help,setHelp]=useState(false), [timed,setTimed]=useState(false);
 useEffect(()=>{let dead=false; import('./simulator').then(async ({Simulator})=>{const engine=await Simulator.create(mount.current!,v=>{if(!dead){setS(v);if(v.view)setView(v.view)}});if(dead)engine.dispose();else sim.current=engine;}).catch(e=>setS(v=>({...v,message:`Unable to start 3D: ${e.message}. Please reload in a WebGL2-capable browser.`})));return()=>{dead=true;sim.current?.dispose()};},[]);
 const start=()=>sim.current?.toggle();
 return <main className="sim-app">
  <header className="topbar"><div className="brand"><span className="brand-icon">D<span>›</span></span><div><h1>DECODE<span className="brand-divider"> / </span><span className="subbrand">SIMULATOR</span></h1><p>FIRST TECH CHALLENGE · 2025–26</p></div></div><div className="connection"><span className={s.controller?'status-dot':'status-dot neutral'}/><Gamepad2 size={17}/><span>{s.controller||'Connect a controller'}</span></div><button className="icon-button" aria-label="Show controls and simulation details" onClick={()=>setHelp(!help)}><Keyboard size={20}/></button></header>
  <div className="workspace"><section className="arena"><div ref={mount} className="canvas-mount" aria-label="Interactive 3D FTC DECODE field"/><div className="arena-top"><div className="session-label"><span className="status-dot"/> {timed?'TELEOP PRACTICE':'FREE DRIVE'} <span className="small-separator">/</span> BLUE ALLIANCE</div><div className="view-picker">{['Field','Follow','Top'].map(v=><button key={v} className={view===v?'selected':''} onClick={()=>{setView(v);sim.current?.configure({view:v})}}>{v}</button>)}</div></div>
  <div className="scoreboard"><div className="alliance"><span className="blue-mark"/>BLUE <strong>{s.score.toString().padStart(2,'0')}</strong></div><div className="clock"><span>{timed?'TELEOP':'PRACTICE'}</span><strong>{timed?`${Math.floor(s.time/60)}:${Math.ceil(s.time%60).toString().padStart(2,'0')}`:'∞'}</strong><small>{s.ended?'SESSION COMPLETE':s.running?'IN PROGRESS':'READY TO DRIVE'}</small></div><div className="motif"><span>MOTIF · 21</span><div><i className="ball G"/><i className="ball P"/><i className="ball P"/></div></div></div>
  {!s.ready&&<div className="loading-message" role="status">{s.message}</div>}
  {s.ready&&!s.running&&<div className="start-overlay"><div className="eyebrow">{s.ended?'SESSION COMPLETE':'YOUR DRIVER STATION'}</div><h2>{s.ended?`${s.score} points. One more run?`:'Take the controls.'}</h2><p>{s.ended?`${s.classified} classified · ${s.overflow} overflow · ${s.pattern} pattern points`:'Collect. Aim. Launch. Open the gate and go again.'}</p><button className="primary" onClick={()=>{if(s.ended)sim.current?.reset();start()}}><Play size={17} fill="currentColor"/>{s.ended?'Drive again':'Start driving'}<kbd>Enter</kbd></button></div>}
  <div className="field-caption"><span>DECODE</span><small>12 × 12 FT FIELD</small></div>
  <div className="arena-bottom"><div className="telemetry"><span className="status-dot"/><span>{s.speed.toFixed(2)} <small>m/s</small></span><span className="telemetry-divider"/><span>{s.inZone?'LAUNCH ZONE':'COLLECTION ZONE'}</span></div><div className="camera-buttons"><button className="icon-button" aria-label={sound?'Mute sounds':'Enable sounds'} onClick={()=>{setSound(!sound);sim.current?.configure({sound:!sound})}}>{sound?<Volume2 size={18}/>:<VolumeX size={18}/>}</button><button className="icon-button" aria-label="Full screen" onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{})}}><Maximize size={18}/></button></div></div>
  <div className="touch-controls"><button onPointerDown={()=>sim.current?.press('KeyW',true)} onPointerUp={()=>sim.current?.press('KeyW',false)} onPointerCancel={()=>sim.current?.press('KeyW',false)}>↑</button><button onPointerDown={()=>sim.current?.press('KeyA',true)} onPointerUp={()=>sim.current?.press('KeyA',false)}>←</button><button onPointerDown={()=>sim.current?.press('KeyS',true)} onPointerUp={()=>sim.current?.press('KeyS',false)}>↓</button><button onPointerDown={()=>sim.current?.press('KeyD',true)} onPointerUp={()=>sim.current?.press('KeyD',false)}>→</button><button onClick={()=>sim.current?.shoot()}>Shoot</button></div>
  </section>
  <aside className="driver-panel"><div className="panel-heading"><span>DRIVER STATION</span><span className="live-badge">● LIVE</span></div><div className="robot-title"><div className="robot-number">01</div><div><h2>Blue Mecanum</h2><p>Holonomic drive · 3-artifact intake</p></div></div>
  <section className="panel-section"><div className="section-title"><h3>Magazine</h3><span>{s.magazine.length} / 3</span></div><div className="magazine">{[0,1,2].map(i=><div className={'magazine-slot '+(s.magazine[i]||'empty')} key={i}>{s.magazine[i]?<i className={'large-ball '+s.magazine[i]}/>:<span>+</span>}<small>{i===0?'NEXT':`0${i+1}`}</small></div>)}</div><p className="hint"><span className="status-dot"/>Auto intake on · drive into an artifact</p></section>
  <section className="panel-section"><div className="section-title"><h3>Launcher</h3><Crosshair size={17}/></div><div className="setting-row"><label htmlFor="aim-assist">Aim assist</label><Switch id="aim-assist" checked={assist} onCheckedChange={v=>{setAssist(v);sim.current?.configure({assist:v})}}/></div><div className="power-label"><label id="power-label">Launch speed</label><span>{assist?'AUTO':`${power.toFixed(1)} m/s`}</span></div><Slider aria-labelledby="power-label" min={3} max={10} step={0.1} value={[power]} disabled={assist} onValueChange={v=>{let n=Array.isArray(v)?v[0]:v;setPower(n);sim.current?.configure({power:n})}}/><button className="shoot-button" disabled={!s.running||!s.magazine.length} onClick={()=>sim.current?.shoot()}>Launch artifact <kbd>SPACE</kbd></button></section>
  <section className="panel-section"><div className="section-title"><h3>Classifier</h3><span>{s.ramp.length} / 9</span></div><div className="ramp-slots">{Array.from({length:9},(_,i)=><span key={i} className={'ramp-slot '+(s.ramp[i]||'')} title={`Slot ${i+1}: ${s.ramp[i]||'empty'}, target ${i%3===0?'green':'purple'}`}>{s.ramp[i]?<i className={'ball '+s.ramp[i]}/>:<i className={'ghost-ball '+(i%3===0?'G':'P')}/>}</span>)}</div><div className="gate-row"><span className={s.gate>.3?'gate-status open':'gate-status'}>◈ Gate {s.gate>.3?'open':'closed'}</span><button disabled={!s.running||!s.nearGate} onPointerDown={()=>sim.current?.press('KeyF',true)} onPointerUp={()=>sim.current?.press('KeyF',false)} onPointerLeave={()=>sim.current?.press('KeyF',false)}>Hold <kbd>F</kbd></button></div><p className="hint">Drive to the blue gate. Hold F to push it open and release the balls.</p></section>
  <section className="session-stats"><div><span>Classified</span><strong>{s.classified}</strong></div><div><span>Overflow</span><strong>{s.overflow}</strong></div><div><span>Accuracy</span><strong>{s.shots?Math.round(s.hits/s.shots*100):0}<small>%</small></strong></div></section>
  <div className="session-actions"><div className="setting-row"><label htmlFor="timed">2-minute timed practice</label><Switch id="timed" checked={timed} onCheckedChange={v=>{setTimed(v);sim.current?.configure({timed:v});sim.current?.reset()}}/></div><div className="action-buttons"><button onClick={start} disabled={!s.ready||s.ended}>{s.running?<Pause size={16}/>:<Play size={16}/>} {s.running?'Pause':'Drive'}</button><button onClick={()=>sim.current?.reset()}><RotateCcw size={16}/>Reset field</button></div></div>
  </aside></div>
  <footer className="control-strip"><div><Keyboard size={19}/><b>CONTROLS</b></div><span><kbd>W A S D</kbd> Move</span><span><kbd>Q E</kbd> Turn</span><span><kbd>SPACE</kbd> Shoot</span><span><kbd>F</kbd> Gate</span><span><kbd>SHIFT</kbd> Precision</span><button onClick={()=>setHelp(!help)}>Controller guide <ChevronRight size={15}/></button></footer><div className="status-strip"><span role="status">{s.ready?s.message:'Loading simulation'}</span><span>Unofficial DECODE practice · simplified field model</span></div>
  {help&&<div className="help-panel"><button className="close-help" onClick={()=>setHelp(false)} aria-label="Close controls">×</button><Gamepad2 size={26}/><h2>Made for your controller.</h2><p>Connect your PS5 DualSense by USB or Bluetooth, then press any button. A standard browser gamepad mapping is required.</p><div className="control-guide"><span>Left stick</span><b>Move on the field</b><span>Right stick ↔</span><b>Turn robot</b><span>R2 / Cross</span><b>Launch artifact</b><span>Square (hold)</span><b>Push nearby gate</b><span>L2</span><b>Precision driving</b><span>Triangle</span><b>Change camera</b><span>Options / Enter</span><b>Pause / resume</b></div><h3>Simulation notes</h3><p>Rapier rigid-body physics at 120 Hz; gravity, momentum, friction, bouncing, and continuous collision detection. Robot traction and gate linkage are approximated. Classifier routing is scripted after goal entry. This is solo driver practice, not a complete referee or autonomous match simulator.</p><a href="https://ftc-resources.firstinspires.org/ftc/archive/2026/game/cm-html/DECODE_Competition_Manual_TU32.htm" target="_blank" rel="noreferrer">Read the official TU32 manual <ArrowUpRight size={16}/></a></div>}
 </main>
}
