import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import { driveImpulse, launchVelocity, inLaunchZone, patternPoints, deadzone } from './physics';
export type Snapshot={view?:string;ready:boolean;score:number;classified:number;overflow:number;pattern:number;magazine:string[];ramp:string[];speed:number;time:number;running:boolean;gate:number;nearGate:boolean;controller:string;message:string;shots:number;hits:number;ended:boolean;inZone:boolean};
type Ball={body:RAPIER.RigidBody;mesh:THREE.Mesh;color:string;state:'free'|'held'|'flight'|'transit'|'ramp';previousY:number;wait:number;side:number};
type Gate={body:RAPIER.RigidBody;mesh:THREE.Group;angle:number;velocity:number;side:number};
type Options={assist:boolean;power:number;view:string;sound:boolean;timed:boolean};
const H=1.8288, R=.0635, DT=1/120;
export class Simulator{
 static async create(el:HTMLElement,cb:(s:Snapshot)=>void){await RAPIER.init();return new Simulator(el,cb)}
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(43,1,.03,80);renderer:THREE.WebGLRenderer;world=new RAPIER.World({x:0,y:-9.81,z:0});
 robot!:RAPIER.RigidBody;robotMesh=new THREE.Group();turret=new THREE.Group();wheels:THREE.Mesh[]=[];balls:Ball[]=[];gates:Gate[]=[];inventory:Ball[]=[];ramp:Ball[]=[];
 options:Options={assist:true,power:6.3,view:'Field',sound:true,timed:false};keys=new Set<string>();s:Snapshot={ready:true,score:0,classified:0,overflow:0,pattern:0,magazine:[],ramp:[],speed:0,time:120,running:false,gate:0,nearGate:false,controller:'',message:'WASD to drive. Space to launch. Aim assist is on.',shots:0,hits:0,ended:false,inZone:true};
 yaw=0;frame=0;last=0;accum=0;uiClock=0;shotClock=0;gateClock=0;disposed=false;padButtons:boolean[]=[];resize:ResizeObserver;audio?:AudioContext;trajectory:THREE.Line;contextLife=new AbortController();
 constructor(private el:HTMLElement,private cb:(s:Snapshot)=>void){
 this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.25;el.appendChild(this.renderer.domElement);
 this.scene.background=new THREE.Color('#26343d');this.scene.fog=new THREE.Fog('#26343d',10,25);this.scene.add(new THREE.HemisphereLight('#d4e8ff','#444c44',2));let sun=new THREE.DirectionalLight('#fff7dc',3.5);sun.position.set(-3,7,4);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-4,right:4,top:4,bottom:-4,near:.1,far:20});sun.shadow.bias=-.0003;sun.shadow.normalBias=.015;this.scene.add(sun);let fill=new THREE.DirectionalLight('#a2c4ff',1.5);fill.position.set(5,3,-4);this.scene.add(fill);
 this.world.timestep=DT;this.buildField();this.buildRobot();this.trajectory=new THREE.Line(new THREE.BufferGeometry(),new THREE.LineDashedMaterial({color:'#dcff92',dashSize:.06,gapSize:.055,transparent:true,opacity:.65}));this.scene.add(this.trajectory);
 this.resize=new ResizeObserver(()=>this.resizeCanvas());this.resize.observe(el);this.resizeCanvas();window.addEventListener('keydown',this.keydown);window.addEventListener('keyup',this.keyup);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);this.reset();this.camera.position.set(0,5.2,5.3);this.camera.lookAt(0,0,0);this.registerTools();this.frame=requestAnimationFrame(this.tick);
 }
 mat(color:THREE.ColorRepresentation,metalness=0,roughness=.6){return new THREE.MeshStandardMaterial({color,metalness,roughness})}
 box(x:number,y:number,z:number,w:number,h:number,d:number,color:THREE.ColorRepresentation,physical=false,parent:THREE.Object3D=this.scene){let mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),this.mat(color,color==='#9caeb5'?.75:0));mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);if(physical)this.world.createCollider(RAPIER.ColliderDesc.cuboid(w/2,h/2,d/2).setTranslation(x,y,z).setFriction(.6));return mesh}
 label(text:string,x:number,y:number,z:number,size:number,color='#dae4e8',flat=false){let c=document.createElement('canvas');c.width=1024;c.height=256;let ctx=c.getContext('2d')!;ctx.font='bold 100px Arial';ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,128);let texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;let m=new THREE.Mesh(new THREE.PlaneGeometry(size,size/4),new THREE.MeshBasicMaterial({map:texture,transparent:true,depthWrite:false,side:THREE.DoubleSide}));m.position.set(x,y,z);if(flat)m.rotation.x=-Math.PI/2;this.scene.add(m);return m}
 line(a:THREE.Vector3,b:THREE.Vector3,width:number,color:string){let dist=a.distanceTo(b),m=this.box((a.x+b.x)/2,.008,(a.z+b.z)/2,width,.005,dist,color);m.rotation.y=Math.atan2(b.x-a.x,b.z-a.z);return m}
 buildField(){
 this.box(0,-.1,0,5.8,.1,5.8,'#18232b',true);this.box(0,-.045,0,H*2,.09,H*2,'#535d60',true);
 for(let x=0;x<6;x++)for(let z=0;z<6;z++){let m=this.box(-H+(x+.5)*.6096,.001,-H+(z+.5)*.6096,.604,.006,.604,(x+z)%2?'#687477':'#626e72');m.receiveShadow=true;}
 for(let side of [-1,1]){
 this.box(side*(H+.025),.14,0,.045,.28,H*2+.1,'#53616a',true);this.box(0,.14,side*(H+.025),H*2,.28,.045,'#53616a',true);
 this.box(side*(H+.025),.29,0,.055,.035,H*2+.1,'#b6c3c6');this.box(0,.29,side*(H+.025),H*2,.035,.055,'#b6c3c6');
 for(let p=-H;p<=H+.01;p+=.6096){this.box(side*(H+.02),.17,p,.068,.33,.055,'#263840');this.box(p,.17,side*(H+.02),.055,.33,.068,'#263840');}
 }
 // The two taped triangular launch zones share the field's center line axis.
 this.line(new THREE.Vector3(-H,0,-H),new THREE.Vector3(0,0,0),.025,'#e4e6db');this.line(new THREE.Vector3(H,0,-H),new THREE.Vector3(0,0,0),.025,'#e4e6db');this.line(new THREE.Vector3(-.6096,0,H),new THREE.Vector3(0,0,H-.6096),.025,'#e4e6db');this.line(new THREE.Vector3(.6096,0,H),new THREE.Vector3(0,0,H-.6096),.025,'#e4e6db');
 this.label('DECODE',0,.011,-.55,1.1,'#929e9d',true);this.label('FIRST TECH CHALLENGE',0,.012,-.75,.9,'#8b989b',true);
 for(let side of [-1,1]){
 const color=side===1?'#568ced':'#e65f56',gx=side*1.46,gz=-1.49;
 // Open triangular goal: two back walls and a diagonal front wall, with no top collider.
 this.box(gx,.492,gz-.27,.58,.985,.026,color,true);this.box(gx+side*.27,.492,gz,.026,.985,.56,color,true);
 let front=this.box(gx-side*.015,.43,gz+.015,.026,.86,.76,color);front.rotation.y=side*Math.PI/4;let desc=RAPIER.ColliderDesc.cuboid(.013,.43,.38).setTranslation(front.position.x,front.position.y,front.position.z).setRotation({x:0,y:Math.sin(side*Math.PI/8),z:0,w:Math.cos(side*Math.PI/8)});this.world.createCollider(desc);
 this.box(gx,.985,gz-.27,.62,.022,.034,'#ced8d7');this.box(gx+side*.27,.985,gz,.034,.022,.6,'#ced8d7');
 this.box(gx,1.16,gz-.29,.62,.37,.035,'#e4e6dd',true);this.label('FIRST',gx,1.22,gz-.265,.43,'#243b4a');this.label('TECH CHALLENGE',gx,1.11,gz-.262,.48,'#243b4a');
 // Fiducial-style contrast target, decorative rather than a valid AprilTag.
 this.box(gx-side*.12,.58,gz+.17,.18,.18,.008,'#e8e9df');this.box(gx-side*.12,.58,gz+.179,.12,.12,.008,'#17242a');this.box(gx-side*.145,.595,gz+.185,.04,.05,.008,'#e8e9df');
 // Classifier chute is at the field side: inclined physical rails and gravity-close gate.
 let ramp=this.box(side*1.61,.285,-.39,.23,.022,1.47,'#a0afb0');ramp.rotation.x=.115;
 let rd=RAPIER.ColliderDesc.cuboid(.115,.011,.735).setTranslation(side*1.61,.285,-.39).setRotation({x:Math.sin(.115/2),y:0,z:0,w:Math.cos(.115/2)}).setFriction(.16);this.world.createCollider(rd);
 for(let dx of [-.125,.125]){let rail=this.box(side*1.61+dx,.37,-.39,.018,.1,1.47,'#aebbbd');rail.rotation.x=.115;this.world.createCollider(RAPIER.ColliderDesc.cuboid(.009,.05,.735).setTranslation(rail.position.x,rail.position.y,rail.position.z).setRotation({x:Math.sin(.115/2),y:0,z:0,w:Math.cos(.115/2)}));}
 for(let z of [-.95,.2])this.box(side*1.61,.09,z,.025,.18,.025,'#9caeb5',true);
 let body=this.world.createRigidBody(RAPIER.RigidBodyDesc.kinematicPositionBased().setTranslation(side*1.61,.205,.36));this.world.createCollider(RAPIER.ColliderDesc.cuboid(.14,.072,.015),body);let gate=new THREE.Group();this.box(0,0,0,.28,.144,.03,color,false,gate);this.box(-side*.14,-.07,.05,.1,.03,.17,'#dbe6e4',false,gate);this.scene.add(gate);this.gates.push({body,mesh:gate,angle:0,velocity:0,side});
 this.line(new THREE.Vector3(side*1.31,0,.21),new THREE.Vector3(side*1.31,0,.49),.025,color);this.label('GATE',side*1.15,.015,.37,.32,color,true);
 for(let dx of [-.23,.23])this.box(side*1.1+dx,.012,1.49,.018,.007,.46,color);for(let z of [1.26,1.72])this.box(side*1.1,.012,z,.48,.007,.018,color);this.label('BASE',side*1.1,.016,1.48,.33,color,true);
 this.line(new THREE.Vector3(side*1.25,0,.62),new THREE.Vector3(side*H,0,.62),.023,'#dce1d9');this.line(new THREE.Vector3(side*1.25,0,.62),new THREE.Vector3(side*1.25,0,1.18),.023,'#dce1d9');this.label('RECYCLE',side*1.59,.014,.98,.4,'#b0bec1',true);
 for(let z of [-.55,.1,.75])this.box(side*.78,.012,z,.254,.006,.021,'#dce1d9');
 }
 }
 buildRobot(){this.robot=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(0,.13,1.35).setLinearDamping(.1).setAngularDamping(4).setCcdEnabled(true));this.world.createCollider(RAPIER.ColliderDesc.cuboid(.19,.11,.19).setMass(14).setFriction(.2),this.robot);this.robot.setEnabledRotations(false,true,false,true);
 this.box(0,0,0,.35,.14,.34,'#1b242b',false,this.robotMesh);this.box(0,.083,0,.32,.02,.33,'#a7b6ba',false,this.robotMesh);this.box(0,-.025,.184,.35,.095,.015,'#437ce3',false,this.robotMesh);this.box(-.179,0,0,.025,.11,.38,'#437ce3',false,this.robotMesh);this.box(.179,0,0,.025,.11,.38,'#437ce3',false,this.robotMesh);
 for(let x of [-.2,.2])for(let z of [-.13,.13]){let wheel=new THREE.Mesh(new THREE.CylinderGeometry(.072,.072,.055,20),this.mat('#151e21',.1,.85));wheel.rotation.z=Math.PI/2;wheel.position.set(x,-.052,z);wheel.castShadow=true;this.robotMesh.add(wheel);this.wheels.push(wheel);for(let i=0;i<8;i++){let roller=new THREE.Mesh(new THREE.CylinderGeometry(.014,.014,.066,8),this.mat('#777f7c',.5));roller.rotation.x=Math.PI/4;roller.position.set(Math.sin(i*Math.PI/4)*.058,0,Math.cos(i*Math.PI/4)*.058);wheel.add(roller)}}
 for(let x of [-.14,.14])for(let z of [-.13,.1]){this.box(x,.16,z,.021,.21,.021,'#9caeb5',false,this.robotMesh)}
 this.box(0,.235,-.025,.31,.02,.29,'#394851',false,this.robotMesh);this.turret.position.y=.24;this.box(0,.027,0,.19,.025,.23,'#a9b8b9',false,this.turret);for(let x of [-.07,.07]){this.box(x,.067,-.075,.03,.07,.22,'#1c2c36',false,this.turret)}this.box(0,.032,-.18,.17,.04,.03,'#cafb63',false,this.turret);this.robotMesh.add(this.turret);
 let intake=new THREE.Mesh(new THREE.CylinderGeometry(.038,.038,.28,16),this.mat('#c4f86b'));intake.rotation.z=Math.PI/2;intake.position.set(0,-.045,-.22);this.robotMesh.add(intake);this.scene.add(this.robotMesh);
 }
 spawn(color:string,x:number,y:number,z:number){let body=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,y,z).setCcdEnabled(true).setLinearDamping(.035).setAngularDamping(.25));this.world.createCollider(RAPIER.ColliderDesc.ball(R).setMass(.065).setFriction(.45).setRestitution(.48),body);let mesh=new THREE.Mesh(new THREE.SphereGeometry(R,24,16),this.mat(color==='G'?'#85cf39':'#9050d9',.04,.34));mesh.castShadow=true;mesh.receiveShadow=true;this.scene.add(mesh);let b:Ball={body,mesh,color,state:'free',previousY:y,wait:0,side:1};this.balls.push(b);return b}
 reset(){for(let b of this.balls){this.world.removeRigidBody(b.body);this.scene.remove(b.mesh);b.mesh.geometry.dispose();(b.mesh.material as THREE.Material).dispose()}this.balls=[];this.inventory=[];this.ramp=[];this.keys.clear();this.yaw=0;this.robot.setTranslation({x:0,y:.14,z:1.34},true);this.robot.setRotation({x:0,y:0,z:0,w:1},true);this.robot.setLinvel({x:0,y:0,z:0},true);this.robot.setAngvel({x:0,y:0,z:0},true);for(let g of this.gates){g.angle=0;g.velocity=0;g.body.setTranslation({x:g.side*1.61,y:.205,z:.36},true)}
 for(let side of [-1,1])for(let z of [-.55,.1,.75])for(let i=0;i<3;i++)this.spawn(i===1?'G':'P',side*.78+(i-1)*.15,.08,z);
 for(let i=0;i<15;i++)this.spawn(i%3===1?'G':'P',(i%2?1:-1)*(1.32+Math.floor(i/6)*.16),.09+Math.floor(i/10)*.15,1.1+(Math.floor(i/2)%3)*.17);
 for(let color of ['P','G','P']){let b=this.spawn(color,0,1,0);b.state='held';b.body.setEnabled(false);b.mesh.visible=false;this.inventory.push(b)}
 Object.assign(this.s,{score:0,classified:0,overflow:0,pattern:0,speed:0,time:120,running:false,gate:0,nearGate:false,message:'WASD to drive. Space to launch. Aim assist is on.',shots:0,hits:0,ended:false});this.shotClock=0;this.accum=0;this.emit();}
 configure(v:Partial<Options>){this.options={...this.options,...v};}
 press(k:string,v:boolean){if(v)this.keys.add(k);else this.keys.delete(k)}
 keydown=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest('input,textarea,[role="switch"],[role="slider"]'))return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','KeyF','KeyQ','KeyE'].includes(e.code))e.preventDefault();if(!e.repeat){if(e.code==='Enter')this.toggle();if(e.code==='KeyC')this.options.view=this.options.view==='Field'?'Follow':this.options.view==='Follow'?'Top':'Field';if(e.code==='Escape'&&this.s.running)this.toggle()}this.keys.add(e.code)};
 keyup=(e:KeyboardEvent)=>this.keys.delete(e.code);blur=()=>{this.keys.clear();if(this.s.running){this.s.running=false;this.s.message='Paused while the game is unfocused.';this.emit()}};visibility=()=>{if(document.hidden)this.blur()};
 toggle(){if(this.s.ended)return;this.s.running=!this.s.running;this.keys.clear();if(this.s.running){if(!this.audio&&this.options.sound){try{this.audio=new AudioContext()}catch{}}this.audio?.resume().catch(()=>{});this.s.message='Drive over artifacts to collect. Space / R2 to shoot.'}else this.s.message='Paused · Enter to resume';this.emit()}
 sound(freq=450){if(!this.options.sound||!this.audio)return;let o=this.audio.createOscillator(),gain=this.audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,this.audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,this.audio.currentTime+.12);gain.gain.setValueAtTime(.06,this.audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,this.audio.currentTime+.15);o.connect(gain).connect(this.audio.destination);o.start();o.stop(this.audio.currentTime+.16)}
 getLaunch(){let p=this.robot.translation();let yaw=this.options.assist?Math.atan2(-(1.55-p.x),-(-1.59-p.z)):this.yaw;let x=p.x-Math.sin(yaw)*.23,z=p.z-Math.cos(yaw)*.23;let start={x,y:p.y+.27,z};let velocity=this.options.assist?launchVelocity(start,{x:1.55,y:1.055,z:-1.59}):{x:-Math.sin(yaw)*this.options.power*Math.cos(.88)+this.robot.linvel().x,y:this.options.power*Math.sin(.88),z:-Math.cos(yaw)*this.options.power*Math.cos(.88)+this.robot.linvel().z};return {start,velocity,yaw}}
 shoot(){if(!this.s.running||!this.inventory.length||this.shotClock>0)return;let p=this.robot.translation();if(!inLaunchZone(p.x,p.z)){this.s.message='Move into a taped launch triangle before shooting.';this.emit();return}let b=this.inventory.shift()!,{start,velocity}=this.getLaunch();b.state='flight';b.previousY=start.y;b.body.setEnabled(true);b.body.setTranslation(start,true);b.body.setLinvel(velocity,true);b.body.setAngvel({x:10,y:0,z:0},true);b.mesh.visible=true;this.shotClock=.42;this.s.shots++;this.sound(350);this.s.message='Artifact launched';this.emit()}
 step(){
 const pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p&&p.connected);this.s.controller=pad?(pad.mapping==='standard'?'Controller connected':'Nonstandard controller · use keyboard'):'';let axes=pad?.mapping==='standard'?pad.axes:[],buttons=pad?.mapping==='standard'?pad.buttons:[];
 if(buttons[9]?.pressed&&!this.padButtons[9])this.toggle();if(buttons[3]?.pressed&&!this.padButtons[3])this.options.view=this.options.view==='Field'?'Follow':this.options.view==='Follow'?'Top':'Field';this.padButtons=buttons.map(b=>b.pressed);
 if(!this.s.running)return;
 this.shotClock=Math.max(0,this.shotClock-DT);let left=Number(this.keys.has('KeyA')||this.keys.has('ArrowLeft')),right=Number(this.keys.has('KeyD')||this.keys.has('ArrowRight')),up=Number(this.keys.has('KeyW')||this.keys.has('ArrowUp')),down=Number(this.keys.has('KeyS')||this.keys.has('ArrowDown'));let x=right-left+deadzone(axes[0]||0),z=down-up+deadzone(axes[1]||0);let len=Math.hypot(x,z);if(len>1){x/=len;z/=len}let turn=Number(this.keys.has('KeyQ'))-Number(this.keys.has('KeyE'))-deadzone(axes[2]||0);let precision=this.keys.has('ShiftLeft')||this.keys.has('ShiftRight')||(buttons[6]?.value||0)>.2;let p=this.robot.translation(),vel=this.robot.linvel();let impulse=driveImpulse(vel,{x:x*(precision?.45:1.65),z:z*(precision?.45:1.65)},this.robot.mass(),DT);if(p.y<.22)this.robot.applyImpulse({x:impulse.x,y:0,z:impulse.z},true);let angular=this.robot.angvel();this.robot.applyTorqueImpulse({x:0,y:Math.max(-.1,Math.min(.1,(turn*2.6-angular.y)*.025)),z:0},true);
 let q=this.robot.rotation();this.yaw=Math.atan2(2*(q.w*q.y+q.x*q.z),1-2*(q.y*q.y+q.z*q.z));this.s.inZone=inLaunchZone(p.x,p.z);this.s.speed=Math.hypot(vel.x,vel.z);
 if(this.keys.has('Space')||buttons[7]?.pressed||buttons[0]?.pressed)this.shoot();
 this.s.nearGate=Math.hypot(p.x-1.36,p.z-.36)<.38;
 for(let g of this.gates){let pushing=g.side===1&&this.s.nearGate&&(this.keys.has('KeyF')||buttons[2]?.pressed);let acceleration=(pushing?14:0)-8*Math.sin(g.angle+.15)-5*g.velocity;g.velocity+=acceleration*DT;g.angle=Math.max(0,Math.min(1.4,g.angle+g.velocity*DT));if(g.angle===0||g.angle===1.4)g.velocity=0;g.body.setNextKinematicTranslation({x:g.side*1.61,y:.205+Math.sin(g.angle)*.19,z:.36});g.body.setNextKinematicRotation({x:Math.sin(g.angle/2),y:0,z:0,w:Math.cos(g.angle/2)});if(g.side===1)this.s.gate=g.angle/1.4;}
 this.world.step();
 for(let b of this.balls){if(b.state==='held')continue;let pos=b.body.translation();if(b.state==='transit'){b.wait-=DT;if(b.wait<=0){b.body.setEnabled(true);b.body.setTranslation({x:b.side*1.61,y:.5,z:-1.03},true);b.body.setLinvel({x:0,y:0,z:.18},true);b.mesh.visible=true;b.state='ramp';}continue}
 if(b.state==='flight'&&b.previousY>1.01&&pos.y<=1.01&&b.body.linvel().y<0){for(let side of [-1,1]){let u=(pos.x-side*1.46)*side,v=pos.z+1.49;if(u>-.22&&u<.22&&v>-.22&&v<.22&&v<u-.035){b.side=side;b.state='transit';b.wait=.5;b.body.setEnabled(false);b.mesh.visible=false;if(side===1){this.s.hits++;let retained=this.ramp.length<9;if(retained){this.ramp.push(b);this.s.classified++;this.s.score+=3}else{this.s.overflow++;this.s.score++;b.wait=.25;b.state='free';b.body.setEnabled(true);b.body.setTranslation({x:1.61,y:.25,z:.55},true);b.body.setLinvel({x:0,y:0,z:.5},true);b.mesh.visible=true}this.s.message=retained?'+3 · Artifact classified':'+1 · Overflow — open the gate to clear the ramp';this.sound(800)}break}}}
 b.previousY=pos.y;if(b.state==='flight'&&pos.y<.1)b.state='free';if(b.state==='ramp'&&pos.z>.48){b.state='free';this.ramp=this.ramp.filter(v=>v!==b);this.s.message='Gate released an artifact. Collect it from the return lane.'}
 if(b.state==='free'&&pos.y<.17&&this.inventory.length<3){let dx=pos.x-p.x,dz=pos.z-p.z;let forward=-dx*Math.sin(this.yaw)-dz*Math.cos(this.yaw),lateral=dx*Math.cos(this.yaw)-dz*Math.sin(this.yaw);if(forward>.12&&forward<.36&&Math.abs(lateral)<.18){b.state='held';b.body.setEnabled(false);b.mesh.visible=false;this.inventory.push(b);this.s.message=`Collected ${b.color==='G'?'green':'purple'} artifact · ${this.inventory.length}/3`;this.sound(520)}}
 if(pos.y<-.5||Math.abs(pos.x)>2.25||Math.abs(pos.z)>2.25){b.state='free';this.ramp=this.ramp.filter(v=>v!==b);b.body.setTranslation({x:1.4,y:.1,z:1},true);b.body.setLinvel({x:0,y:0,z:0},true);this.s.message='Out-of-field artifact returned to the loading area.'}
 }
 if(this.options.timed){this.s.time=Math.max(0,this.s.time-DT);if(this.s.time===0){this.s.pattern=patternPoints(this.ramp.map(b=>b.color));let base=Math.abs(p.x-1.1)<.035&&Math.abs(p.z-1.49)<.035?10:Math.abs(p.x-1.1)<.4&&Math.abs(p.z-1.49)<.4?5:0;this.s.score+=this.s.pattern+base;this.s.ended=true;this.s.running=false;this.s.message=`Practice complete · ${this.s.pattern} pattern points + ${base} base points`;this.emit()}}
 }
 tick=(t:number)=>{if(this.disposed)return;let elapsed=this.last?Math.min((t-this.last)/1000,.1):0;this.last=t;this.accum+=elapsed;while(this.accum>=DT){this.step();this.accum-=DT}let p=this.robot.translation(),q=this.robot.rotation();this.robotMesh.position.set(p.x,p.y,p.z);this.robotMesh.quaternion.set(q.x,q.y,q.z,q.w);for(let w of this.wheels)w.rotation.x+=this.s.speed*elapsed/.07;let shot=this.getLaunch();this.turret.rotation.y=shot.yaw-this.yaw;
 for(let b of this.balls){if(!b.mesh.visible)continue;let p=b.body.translation(),q=b.body.rotation();b.mesh.position.set(p.x,p.y,p.z);b.mesh.quaternion.set(q.x,q.y,q.z,q.w)}for(let g of this.gates){let p=g.body.translation(),q=g.body.rotation();g.mesh.position.set(p.x,p.y,p.z);g.mesh.quaternion.set(q.x,q.y,q.z,q.w)}
 this.trajectory.visible=this.inventory.length>0&&this.s.inZone;if(this.trajectory.visible){let points=[];for(let i=0;i<40;i++){let t=i*.027,y=shot.start.y+shot.velocity.y*t-4.905*t*t;if(y<.03)break;points.push(new THREE.Vector3(shot.start.x+shot.velocity.x*t,y,shot.start.z+shot.velocity.z*t))}this.trajectory.geometry.dispose();this.trajectory.geometry=new THREE.BufferGeometry().setFromPoints(points);this.trajectory.computeLineDistances()}
 let target=new THREE.Vector3(0,0,-.04),cam=new THREE.Vector3(0,5.2,5.3);if(this.options.view==='Top'){cam.set(0,6.6,.01)}if(this.options.view==='Follow'){cam.set(p.x+Math.sin(this.yaw)*2.1,p.y+1.6,p.z+Math.cos(this.yaw)*2.1);target.set(p.x,.25,p.z-.3)}this.camera.position.lerp(cam,1-Math.exp(-elapsed*4));this.camera.lookAt(target);this.renderer.render(this.scene,this.camera);this.uiClock+=elapsed;if(this.uiClock>.1){this.emit();this.uiClock=0}this.frame=requestAnimationFrame(this.tick)};
 emit(){this.s.view=this.options.view;this.s.magazine=this.inventory.map(b=>b.color);this.s.ramp=this.ramp.map(b=>b.color);this.cb({...this.s,magazine:[...this.s.magazine],ramp:[...this.s.ramp]})}
 resizeCanvas(){let w=this.el.clientWidth,h=this.el.clientHeight;if(w&&h){this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}}
 registerTools(){const context=(document as Document & {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;for(let tool of [{name:'read_practice_state',description:'Read the visible robot practice score, magazine, ramp, and clock.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...this.s})},{name:'set_practice_running',description:'Start or pause the same simulation shown on screen.',inputSchema:{type:'object',properties:{running:{type:'boolean'}},required:['running'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(v:unknown)=>{if(!v||typeof(v as {running?:unknown}).running!=='boolean')throw Error('running must be boolean');if(this.s.ended)throw Error('Session complete. Reset the field first.');if(this.s.running!==(v as {running:boolean}).running)this.toggle();return {running:this.s.running}}}]){try{Promise.resolve(context.registerTool(tool,{signal:this.contextLife.signal})).catch(()=>{})}catch{}}}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.resize.disconnect();window.removeEventListener('keydown',this.keydown);window.removeEventListener('keyup',this.keyup);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);this.contextLife.abort();this.world.free();this.scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();for(let m of Array.isArray(o.material)?o.material:[o.material]){if('map' in m)(m.map as THREE.Texture|null)?.dispose();m.dispose()}}});this.renderer.dispose();this.renderer.domElement.remove();this.audio?.close()}
}
